### ISSUE TITLE
DependsOn does not work

### ISSUE THREAD

**Issue by holubar** [outl1ne/nova-color-field#13]
I cannot seem to get it working under Nova 4. Is it supported? I could really use it in my project.

**Comment by KasparRosin** [comment]
We should have dependsOn support, though I haven't used it myself yet.
Can you share your code/fields setup.

**Comment by holubar** [comment]
This is how I try to use it. Result is, that it's always hidden. This works on all standard Nova fields, only Color is always hidden.

`            Color::make(__('app.background').' - '.__('app.color'), 'properties->section_background_color_code')
                ->compact()
                ->palette(Helpers::tailwind_color_array('simple'))
                ->hideFromIndex()
                ->help(color_palette_link())
                ->dependsOn('type', function (Color $field, NovaRequest $request, FormData $formData) {
                    if (!PageContent::display_heading_first_line_options($formData->type)) {
                        $field->hide();
                    }
                })
`

Thank you for help

**Comment by Tarpsvo** [comment]
Version 2.0.2 ships with improved dependsOn support. Can you try again? Thanks!

**Comment by holubar** [comment]
works :)

**Comment by nieto19** [comment]
Is there a way to change the color value when using depends on?
