### ISSUE TITLE
add checkered background to color preview 

### ISSUE THREAD

**Issue by chrillep** [outl1ne/nova-color-field#14]
would be nice if the background on the preview field was checkered (opacity style).

this would make it easier to see the applied opacity 

like displayed on
https://v1.tailwindcss.com/docs/background-color#class-reference

```html
<td class="w-24 bg-checkered" style="background-color:transparent"></td>
```
<img width="662" alt="Skärmavbild 2022-09-23 kl  19 19 23" src="https://user-images.githubusercontent.com/1267931/192020455-13ed43af-d8fc-413f-889c-b07f7bcd70b2.png">

ref: https://stackoverflow.com/questions/35361986/css-gradient-checkerboard-pattern

**Comment by Tarpsvo** [comment]
Version 2.0.2 now provides a checkered background for the color box. :)
