### ISSUE TITLE
Alpha channel not working properly using `rgba` mode in Nova 3 (v `1.2`)

### ISSUE THREAD

**Issue by reppair** [outl1ne/nova-color-field#16]
Hi there.

There are issues using the alpha channel in `rgba` mode with version `1.2.2` of the package.

### RGBA 

Using `Color::make('rgba')->chrome()->displayAs('rgba')->saveAs('rgba')` and picked example color
`rgba(51, 84, 151, 0.43)`

- **will** properly store the picked color with the alpha channel to the database as json - `{"r":51,"g":84,"b":151,"a":0.43137254901960786}`
- **won't** render the color on details page at all and will show the stored `json` value as string `{"r":51,"g":84,"b":151,"a":0.43137254901960786}` instead as `rgba` value like it really should <img src="https://user-images.githubusercontent.com/10784954/190406769-f0af2b74-c162-4e35-a4d5-d67adb1e9f75.png">
- **won't** load the `rgba` color at all, it always loads black using background-color: rgb(0,0,0) instead of rgba(51, 84, 151, 0.43) <img src="https://user-images.githubusercontent.com/10784954/190407745-1472a5db-59c8-49a8-908e-a53fa0e41291.png">

### Chrome picker issue
When using the chrome picker, it always defaults to the hex mode/ux of the picker. It would be nice if we can control that with the `displayAs()` method is used. For example when having `displayAs('rgba')` chained on the field, when the picker is first opened it should default to the `rgba` ux/styles of the picker instead of `hex`.

Even better we can use that to automatically set the format which should be used to store the value.

**Comment by reppair** [comment]
Was originally part of #12, got a PR for fixing `hex8` but not `rgba`, so extracting it so we can close it but keep this one.

**Comment by marttinnotta** [comment]
Hi

Sadly we do not support Nova 3 any longer. If you need fix for this you might want to fork this from that version and create a fix for your project.
