### ISSUE TITLE
Which vue event is fired when field is updated?

### ISSUE THREAD

**Issue by scramatte** [outl1ne/nova-color-field#21]
Hi,

I'm using your field into my Nova visual Form Builder.
**https://github.com/operativeit/nova-form-designer**

As I need to work directly with the .vue component  normally I've got an handler  @input or @change but it looks that your component ignore them ?

Which vue event is fired when field is updated?
Can you give me an hand?

Regards

**Comment by marttinnotta** [comment]
Hi!

We are using Nova's global event bus for emitting field changes like any other Nova field.
