### ISSUE TITLE
Nova V4 support

### ISSUE THREAD

**Issue by dees040** [outl1ne/nova-color-field#8]
Friendly reminder that Laravel Nova V4 released today. [Upgrade guide](https://nova.laravel.com/docs/4.0/upgrade.html).

**Comment by ianrobertsFF** [comment]
The HTML5 colour picker included with Nova 4 is frankly a bit rubbish.

I should have a Pull Request for Nova 4 compatibility for this plugin finished tomorrow, just got some more testing to do and then mix for prod

**Comment by ianrobertsFF** [comment]
PR Added

**Comment by Tarpsvo** [comment]
Thanks a ton @ianrobertsFF! I merged your PR and tested it - everything works like a charm! :)

It's now released in version 2.0.0!
